<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://tempuri.org/">
<script id="tinyhippos-injected"/>
<!-- messages -->
<wsdl:message name="FuckVasRequest">
    <wsdl:part name="notifications" type="xs:string"/>
</wsdl:message>
<wsdl:message name="FuckVasResponse">
    <wsdl:part name="response" type="xs:string"/>
</wsdl:message>
<!-- port type -->
<wsdl:portType name="MyPort_Type">
     <wsdl:operation name="FuckVas">
       <wsdl:input message="tns:FuckVasRequest"/>
       <wsdl:output message="tns:FuckVasResponse"/>
    </wsdl:operation>
</wsdl:portType>
<!-- port type binding -->
<wsdl:binding name="My_Binding" type="tns:MyPort_Type">
     <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
     <wsdl:operation name="FuckVas">
         <soap:operation soapAction="FuckVas"/>
         <wsdl:input>
          <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
         </wsdl:input>
          <wsdl:output>
               <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
          </wsdl:output>
     </wsdl:operation>
</wsdl:binding>
<!--  service -->
<wsdl:service name="MyService">
    <wsdl:documentation>WSDL File for MyService</wsdl:documentation>
     <wsdl:port binding="tns:My_Binding" name="MyPort">
       <soap:address
        location="http://localhost:8585/wsdl"/>
    </wsdl:port>
</wsdl:service>
</wsdl:definitions>